spring:
  profiles:
    active:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/nawanolza?serverTimezone=Asia/Seoul
    username: ${database-user}
    password: ${database-password}
